# https://doc-snapshots.qt.io/qt6-6.4/supported-platforms.html
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - '10.14'                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - '11.0'                 # [osx and x86_64]

c_compiler_version:        # [osx]
  - 13                     # [osx]
cxx_compiler_version:      # [osx]
  - 13                     # [osx]

# https://bugreports.qt.io/browse/QTBUG-107074
llvmdev:
  - 14                     # [not osx]
  - 13                     # [osx]
clangdev:
  - 14                     # [not osx]
  - 13                     # [osx]
